controller_list:
  - name: fake_chin_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - chin_joint_1
      - chin_joint_2
      - chin_joint_3
      - chin_joint_4
      - chin_joint_5
      - chin_joint_6
  - name: fake_chin_eef_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: chin_arm
    pose: home