arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - chin_joint_1
    - chin_joint_2
    - chin_joint_3
    - chin_joint_4
    - chin_joint_5
    - chin_joint_6
  gains:
    chin_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1