controller_list:
  - name: fake_chin_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - chin_joint_1
      - chin_joint_3
      - chin_joint_6
      - chin_joint_9
      - chin_joint_11
      - chin_joint_13
  - name: fake_chin_eef_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: chin_arm
    pose: home