arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - chin_joint_1
    - chin_joint_3
    - chin_joint_6
    - chin_joint_9
    - chin_joint_11
    - chin_joint_13
  gains:
    chin_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    chin_joint_13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1