<?xml version="1.0"?>
<robot name="chin_arm" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="arm_id" value="chin"/>
  <!--is the robot being simulated in gazebo?-->
  <xacro:property name="gazebo" value="false"/>
  <xacro:property name="safety_distance" value="0"/>
  
  <xacro:property name="link_base_height" value="0.204"/>
  <xacro:property name="link_base_radius" value="0.095"/>
  <xacro:property name="link_1_height" value="0.081"/>
  <xacro:property name="link_1_radius" value="0.066"/>
  <xacro:property name="link_2_height" value="0.082"/>
  <xacro:property name="link_2_radius" value="0.066"/>
  <xacro:property name="link_3_height" value="0.07"/>
  <xacro:property name="link_3_radius" value="0.066"/>
  <xacro:property name="link_4_height" value="0.398"/>
  <xacro:property name="link_4_radius" value="0.055"/>
  <xacro:property name="link_5_height" value="0.065"/>
  <xacro:property name="link_5_radius" value="0.055"/>
  <xacro:property name="link_6_height" value="0.063"/>
  <xacro:property name="link_6_radius" value="0.055"/>
  <xacro:property name="link_7_height" value="0.36"/>
  <xacro:property name="link_7_radius" value="0.045"/>
  <xacro:property name="link_8_height" value="0.083"/>
  <xacro:property name="link_8_radius" value="0.045"/>
  <xacro:property name="link_9_height" value="0.087"/>
  <xacro:property name="link_9_radius" value="0.045"/>
  <xacro:property name="link_10_height" value="0.083"/>
  <xacro:property name="link_10_radius" value="0.045"/>
  <xacro:property name="link_11_height" value="0.087"/>
  <xacro:property name="link_11_radius" value="0.045"/>
  <xacro:property name="link_12_height" value="0.083"/>
  <xacro:property name="link_12_radius" value="0.045"/>
  <xacro:property name="link_13_height" value="0.077"/>
  <xacro:property name="link_13_radius" value="0.045"/>

  <xacro:property name="with_mesh" value="false"/>
  
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  
  <!-- =========================================================== -->
  <!-- add a <collision> tag with a capsule, made from a cylinder  -->
  <!-- with two spheres at its caps. The capsule will always be    -->
  <!-- aligned with the axis of 'direction' you pass along.        -->
  <!--                                                             -->
  <!-- radius: Radii of both the cylinder and both spheres [m]     -->
  <!-- length: Length of the cylinder/distance between the centers -->
  <!--         of the spheres. NOT overall length of capsule!      -->
  <!-- xyz:    Position of the center of the capsule/cylinder      -->
  <!-- direction: One of { x, y, z, -x, -y, -z }                   -->
  <!-- =========================================================== -->
  <xacro:macro name="collision_capsule" params="radius length xyz:='0 0 0' direction:='z'">
    <xacro:property name="r" value="${0.5*pi if 'y' in direction else 0}"/>
    <xacro:property name="p" value="${0.5*pi if 'x' in direction else 0}"/>
    <xacro:property name="y" value="0"/>
    <xacro:property name="x" value="${xyz.split(' ')[0]}"/>
    <xacro:property name="y" value="${xyz.split(' ')[1]}"/>
    <xacro:property name="z" value="${xyz.split(' ')[2]}"/>
    <!--sphere center offsets from center of cylinder-->
    <xacro:property name="sx" value="${0.5*length if 'x' in direction else 0}"/>
    <xacro:property name="sy" value="${0.5*length if 'y' in direction else 0}"/>
    <xacro:property name="sz" value="${0.5*length if 'z' in direction else 0}"/>
    <collision>
      <origin xyz="${x} ${y} ${z}" rpy="${r} ${p} ${y}"/>
      <geometry>
        <cylinder radius="${radius}" length="${length}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="${x+sx} ${y+sy} ${z+sz}"/>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry>
    </collision>
    <collision>
      <origin xyz="${x-sx} ${y-sy} ${z-sz}"/>
      <geometry>
        <sphere radius="${radius}"/>
      </geometry>
    </collision>
  </xacro:macro>
  
  <xacro:macro name="link_with_sc"  params="name link_height link_radius pos_xyz:='0 0 0' pos_rpy:='0 0 0' visual_color:='white' prefix=${arm_id} rpy:='0 0 0' **self_collision_geometries gazebo:=false">
    <!--sub-link defining detailed meshes for collision with environment-->
    <link name="${prefix}_${name}">
      <visual>
	      <origin xyz="${pos_xyz}" rpy="${pos_rpy}"/>
        <geometry>
          <xacro:if value="${with_mesh == 'true'}">
            <mesh filename="package://${description_pkg}/meshes/visual/${name}.dae"/>
          </xacro:if>
          <xacro:unless value="${with_mesh == 'true'}">
            <cylinder length="${link_height}" radius="${link_radius}"/>
          </xacro:unless>
        </geometry>
        <material name="${visual_color}"/>
      </visual>
      <collision>
	      <origin xyz="${pos_xyz}" rpy="${pos_rpy}"/>
        <geometry>
          <xacro:if value="${with_mesh == 'true'}">
            <mesh filename="package://franka_description/meshes/collision/${name}.stl"/>
          </xacro:if>
          <xacro:unless value="${with_mesh == 'true'}">
            <cylinder length="${link_height}" radius="${link_radius}"/>
          </xacro:unless>
        </geometry>
      </collision>
      <xacro:if value="${gazebo}">
        <xacro:inertial_props name="${name}"/>
      </xacro:if>
    </link>
    <!--sub-link defining coarse geometries of real robot's internal self-collision-->
    <link name="${prefix}_${name}_sc">
      <xacro:unless value="${gazebo}">
        <xacro:insert_block name="self_collision_geometries"/>
      </xacro:unless>
    </link>
    <!--fixed joint between both sub-links-->
    <joint name="${prefix}_${name}_sc_joint" type="fixed">
      <origin rpy="${rpy}"/>
      <parent link="${prefix}_${name}"/>
      <child link="${prefix}_${name}_sc"/>
    </joint>
  </xacro:macro>

  <!--fixed link0-->
  <xacro:link_with_sc name="link0" link_height="${link_base_height}" link_radius="${link_base_radius}" pos_xyz="0 0 ${0.5*link_base_height}" visual_color="black" gazebo="${gazebo}">
    <self_collision_geometries/>
  </xacro:link_with_sc>

  <!--link1 to link0-->
  <xacro:link_with_sc name="link1" link_height="${link_1_height}" link_radius="${link_1_radius}" pos_xyz="0 0 ${0.5*link_1_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_1_radius+safety_distance}" length="${link_1_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint1" type="revolute">
    <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi}" soft_upper_limit="${pi}"/>
    <origin rpy="0 0 0" xyz="0 0 ${link_base_height}"/>
    <parent link="${arm_id}_link0"/>
    <child link="${arm_id}_link1"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="0" velocity="0"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link2 to link1-->
  <xacro:link_with_sc name="link2" link_height="${link_2_height}" link_radius="${link_2_radius}" pos_xyz="0 0 ${0.5*link_2_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_2_radius+safety_distance}" length="${link_2_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint2" type="fixed">
    <origin rpy="${-0.5*pi} 0 0" xyz="0 0 ${link_1_height}"/>
    <parent link="${arm_id}_link1"/>
    <child link="${arm_id}_link2"/>
    <axis xyz="0 0 1"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link3 to link2-->
  <xacro:link_with_sc name="link3" link_height="${link_3_height}" link_radius="${link_3_radius}" pos_xyz="0 0 ${0.5*link_3_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_3_radius+safety_distance}" length="${link_3_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint3" type="revolute">
    <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi}" soft_upper_limit="${pi}"/>
    <origin rpy="0 0 0" xyz="0 0 ${link_2_height}"/>
    <parent link="${arm_id}_link2"/>
    <child link="${arm_id}_link3"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="0" velocity="0"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link4 to link3-->
  <xacro:link_with_sc name="link4" link_height="${link_4_height}" link_radius="${link_4_radius}" pos_xyz="0 0 ${0.5*link_4_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_4_radius+safety_distance}" length="${link_4_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint4" type="fixed">
    <origin rpy="${0.5*pi} 0 0" xyz="0 0 ${link_3_height}"/>
    <parent link="${arm_id}_link3"/>
    <child link="${arm_id}_link4"/>
    <axis xyz="0 0 1"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link5 to link4-->
  <xacro:link_with_sc name="link5" link_height="${link_5_height}" link_radius="${link_5_radius}" pos_xyz="0 0 ${0.5*link_5_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_5_radius+safety_distance}" length="${link_5_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint5" type="fixed">
    <origin rpy="${0.5*pi} 0 0" xyz="0 0 ${link_4_height}"/>
    <parent link="${arm_id}_link4"/>
    <child link="${arm_id}_link5"/>
    <axis xyz="0 0 1"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link6 to link5-->
  <xacro:link_with_sc name="link6" link_height="${link_6_height}" link_radius="${link_6_radius}" pos_xyz="0 0 ${0.5*link_6_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_6_radius+safety_distance}" length="${link_6_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint6" type="revolute">
    <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.7925" soft_upper_limit="2.7925"/>
    <origin rpy="0 0 0" xyz="0 0 ${link_5_height}"/>
    <parent link="${arm_id}_link5"/>
    <child link="${arm_id}_link6"/>
    <axis xyz="0 0 1"/>
    <limit lower="-2.7925" upper="2.7925" effort="0" velocity="0"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link7 to link6-->
  <xacro:link_with_sc name="link7" link_height="${link_7_height}" link_radius="${link_7_radius}" pos_xyz="0 0 ${0.5*link_7_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_7_radius+safety_distance}" length="${link_7_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint7" type="fixed">
    <origin rpy="${-0.5*pi} 0 0" xyz="0 0 ${link_6_height}"/>
    <parent link="${arm_id}_link6"/>
    <child link="${arm_id}_link7"/>
    <axis xyz="0 0 1"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link8 to link7-->
  <xacro:link_with_sc name="link8" link_height="${link_8_height}" link_radius="${link_8_radius}" pos_xyz="0 0 ${0.5*link_8_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_8_radius+safety_distance}" length="${link_8_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint8" type="fixed">
    <origin rpy="${-0.5*pi} 0 0" xyz="0 0 ${link_7_height}"/>
    <parent link="${arm_id}_link7"/>
    <child link="${arm_id}_link8"/>
    <axis xyz="0 0 1"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link9 to link8-->
  <xacro:link_with_sc name="link9" link_height="${link_9_height}" link_radius="${link_9_radius}" pos_xyz="0 0 ${0.5*link_9_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_9_radius+safety_distance}" length="${link_9_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint9" type="revolute">
    <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi}" soft_upper_limit="${pi}"/>
    <origin rpy="0 0 0" xyz="0 0 ${link_8_height}"/>
    <parent link="${arm_id}_link8"/>
    <child link="${arm_id}_link9"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="0" velocity="0"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link10 to link9-->
  <xacro:link_with_sc name="link10" link_height="${link_10_height}" link_radius="${link_10_radius}" pos_xyz="0 0 ${0.5*link_10_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_10_radius+safety_distance}" length="${link_10_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint10" type="fixed">
    <origin rpy="${0.5*pi} 0 0" xyz="0 0 ${link_9_height}"/>
    <parent link="${arm_id}_link9"/>
    <child link="${arm_id}_link10"/>
    <axis xyz="0 0 1"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link11 to link10-->
  <xacro:link_with_sc name="link11" link_height="${link_11_height}" link_radius="${link_11_radius}" pos_xyz="0 0 ${0.5*link_11_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_11_radius+safety_distance}" length="${link_11_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint11" type="revolute">
    <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi}" soft_upper_limit="${pi}"/>
    <origin rpy="0 0 0" xyz="0 0 ${link_10_height}"/>
    <parent link="${arm_id}_link10"/>
    <child link="${arm_id}_link11"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="0" velocity="0"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link12 to link11-->
  <xacro:link_with_sc name="link12" link_height="${link_12_height}" link_radius="${link_12_radius}" pos_xyz="0 0 ${0.5*link_12_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_12_radius+safety_distance}" length="${link_12_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint12" type="fixed">
    <origin rpy="${-0.5*pi} 0 0" xyz="0 0 ${link_11_height}"/>
    <parent link="${arm_id}_link11"/>
    <child link="${arm_id}_link12"/>
    <axis xyz="0 0 1"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link13 to link12-->
  <xacro:link_with_sc name="link13" link_height="${link_13_height}" link_radius="${link_13_radius}" pos_xyz="0 0 ${0.5*link_13_height}" gazebo="${gazebo}">
    <self_collision_geometries>
      <xacro:collision_capsule xyz="0 0 0" radius="${link_13_radius+safety_distance}" length="${link_13_height+safety_distance}"/>
    </self_collision_geometries>
  </xacro:link_with_sc>

  <joint name="${arm_id}_joint13" type="revolute">
    <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="${-pi}" soft_upper_limit="${pi}"/>
    <origin rpy="0 0 0" xyz="0 0 ${link_12_height}"/>
    <parent link="${arm_id}_link12"/>
    <child link="${arm_id}_link13"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="0" velocity="0"/>
    <dynamics D="1" K="7000" damping="0.003" friction="0.0" mu_coulomb="0" mu_viscous="16"/>
  </joint>

  <!--link14 to link13-->
  <link name="${arm_id}_link14"/>

  <joint name="${arm_id}_joint14" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 ${link_13_height}"/>
    <parent link="${arm_id}_link13"/>
    <child link="${arm_id}_link14"/>
  </joint>
</robot>
