controller_list:
  - name: fake_chin_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - chin_joint1
      - chin_joint3
      - chin_joint6
      - chin_joint9
      - chin_joint11
      - chin_joint13
  - name: fake_chin_eef_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: chin_arm
    pose: home